# Generated by Django 4.2 on 2023-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0002_records_delete_product_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='country',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='item_type',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='region',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='sales_channel',
            field=models.TextField(max_length=100),
        ),
    ]
