# Generated by Django 4.2 on 2023-04-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpages', '0003_alter_records_country_alter_records_item_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
