# Generated by Django 4.2 on 2023-04-18 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testinput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default="trial", max_length=100),
            preserve_default=False,
        ),
    ]
