# Generated by Django 4.2 on 2023-04-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinput', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(),
        ),
    ]
